version: '3'
services:
  php:
    build:
      context: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker-config/nginx/sites-available:/etc/nginx/sites-available:delegated
    ports:
      - '8000:80'
  db:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: yii2basic
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '33060:3306'
volumes:
    db-data: